name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        npm i
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        npm run deploy
        
